---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 48h0m0s
  type: oci
  url: oci://ghcr.io/rancher/local-path-provisioner/charts
