---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  chart:
    spec: 
      chart: local-path-provisioner
      version: "0.0.32"
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
      reconcileStrategy: ChartVersion
  valuesFrom:
    - kind: ConfigMap
      name: local-path-provisioner-values
      valuesKey: values.yaml

  releaseName: local-path-provisioner
  
  interval: 6h0m0s
  # timeout: 10m0s

  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 2
      remediateLastFailure: true

  upgrade:
    remediation:
      retries: 2
      remediateLastFailure: true
