apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-controller
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/controllers/base/metallb/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m0s
  wait: true
  healthChecks:
    # Wait until the HelmRelease succeeds
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metallb
      namespace: metallb-system
    # Wait until CRDs exists
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ipaddresspools.metallb.io
