apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-addresspool
  namespace: metallb-system
spec:
  addresses:
    - 198.51.100.15-198.51.100.19
    - 198.51.100.2-198.51.100.3
