apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  labels:
    app: jellyfin
    kustomize/app-pv: "true"
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/k8s-local/jellyfin/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-prod-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
  labels:
    app: jellyfin
    kustomize/app-pv: "true"
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/k8s-local/jellyfin/cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-prod-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  labels:
    app: jellyfin
    kustomize/app-pv: "true"
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Prevents deletion of data if PV is deleted
  storageClassName: local-path
  hostPath:
    path: /data/media # Existing directory of media files
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-prod-1
