apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: signalk
  name: signalk
  labels:
    app: signalk
    kustomize/app-pv: "true"
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/k8s-local/signalk/dotsignalk #example: /data/k8s-local/pihole/etc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-prod-1 # example: k8s-node