apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
      - Links:
          - Yle:
              - abbr: Yle
                href: https://yle.fi
  services.yaml: |
    - Services:
        - Jellyfin:
            href: http://jellyfin.home.example.com
            description: Jellyfin Media Server
            icon: jellyfin.png
            siteMonitor: http://jellyfin.jellyfin.svc.cluster.local
        - Signalk:
            href: http://signalk.home.example.com
            description: Signalk Marine Data Server
            icon: https://signalk.org/_astro/favicon.D8Mzuhqg.ico
            siteMonitor: http://signalk.signalk.svc.cluster.local
            
    - Homelab:
        - Pi-hole:
            href: https://pihole.home.example.com/admin/
            description: Pi-hole Local DNS server
            icon: pi-hole.png
            siteMonitor: http://pihole.pihole.svc.cluster.local
        - Omada Controller:
            href: https://omada.home.example.com
            description: TP-Link Omada Software Controller
            icon: omada.png
            siteMonitor: https://omada-controller.omada.svc.cluster.local


    # - My Third Group:
    #     - My Third Service:
    #         href: http://localhost/
    #         description: Homepage is 😎
  widgets.yaml: |
    # - kubernetes:
    #     cluster:
    #       show: false
    #       cpu: false
    #       memory: false
    #       showLabel: false
    #       label: "cluster"
    #     nodes:
    #       show: false
    #       cpu: false
    #       memory: false
    #       showLabel: false
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
        #uptime: true
        refresh: 5000

    - search:
        provider: google
        target: _blank
  docker.yaml: ""
