apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-ns.yaml
  - cert-manager-helmrepository.yaml # cert-manager HelmRepository
  - cert-manager-helmrelease.yaml # cert-manager HelmRelease
