apiVersion: v1
kind: PersistentVolume
metadata:
  name: omada-data
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 8Gi
  local:
    path: /data/k8s-local/omada/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-prod-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: omada-logs
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 4Gi
  local:
    path: /data/k8s-local/omada/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-prod-1

  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
