---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  dependsOn:
    # Ensure that MetalLB is installed before Kong to allow the LoadBalancer service to be created successfully
    - name: metallb
      namespace: metallb-system
  chart:
    spec:
      chart: ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      version: "~0.21.0"
      valuesFiles:
        - values.yaml
  interval: 6h0m0s
  # timeout: 10m0s
  
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 2
      remediateLastFailure: true

  upgrade:
    remediation:
      retries: 2
      remediateLastFailure: true
  
  # values:
  #   crds:
  #     enabled: true
