apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
patches:
  - target:
      kind: HTTPRoute
      name: signalk
      namespace: signalk
      group: gateway.networking.k8s.io
      version: v1
    path: patch-signalk-route.yaml