---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-configs
  interval: 1h0m0s
  path: ./kubernetes/apps/home-dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 15m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
