---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/configs/home-dev
  dependsOn:
    - name: infra-controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age

