# This is a Talos configuration file.
# This file is intended to be used as a patch to the common configuration file.

# Provides machine specific configuration options.
machine:
  certSANs: # Subject Alternative Names for the machine's TLS cert.
    - talos-prod-1.home.example.com
  
  kubelet:
    nodeIP:
      # The `validSubnets` field configures the networks to pick kubelet node IP from.
      validSubnets:
      - 198.51.100.0/24
    
# Used to provide instructions for installations.
  install:
    disk: /dev/vda # The disk to install Talos onto.
    image: factory.talos.dev/metal-installer/7d4c31cbd96db9f90c874990697c523482b2bae27fb4631d5583dcd9c281b1ff:v1.12.5

# Provides cluster specific configuration options.
cluster:
  # Allows running workload on control-plane nodes.
  allowSchedulingOnControlPlanes: true

---
## Configure networking for the node.
# Configure hostname  
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-prod-1
auto: off
---

# Create alias for the network interface Works only when single interface is present.
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
    match: true # as there is a single link only, we can match it this way
---

# Configure static IP address for the host
apiVersion: v1alpha1
kind: LinkConfig
name: net0
addresses:
    - address: 198.51.100.10/24
routes:
    - gateway: 198.51.100.1
---

# Configure DNS for the node
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
    - address: 1.1.1.1
    - address: 1.0.0.1
# searchDomains: # optional
#    domains:
#        - example.org
#        - example.com
#    disableDefault: false
---

# Configure timesync for the node
apiVersion: v1alpha1
kind: TimeSyncConfig
ntp:
    servers:
        - time.cloudflare.com
---

# Set static host entries for the node (/etc/hosts)
apiVersion: v1alpha1
kind: StaticHostConfig
name: 198.51.100.10 # IP address (IPv4 or IPv6) to map the hostnames to.
# List of hostnames to map to the IP address.
hostnames:
    - talos-prod-1.home.example.com
    - kube.home.example.com