---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-controllers
  - name: infra-configs
  - name: apps
  interval: 1h0m0s
  path: ./kubernetes/clusters/home-prod/overlays
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  