apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure overlay
  - ../../infrastructure/overlays/home-prod
  # Applications overlay
  - ../../apps/home-prod

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true

images:
  - name: docker.io/tihal/omada-controller
    newTag: "5.15.24.18"
  - name: docker.io/jellyfin/jellyfin
    newTag: "10.10.7"
  - name: docker.io/pihole/pihole
    newTag: "2025.08.0"
  - name: docker.io/teklife/homepage
    newTag: latest  
  - name: docker.io/teklife/signalk
    newTag: latest

transformers:
  - transformers/pv-labeler-transformer.yaml # Add label to all pvs to let pvc-update-transformer.yaml select them
  - transformers/pvc-labeler-transformer.yaml # Add label to all pvcs to let pvc-update-transformer.yaml select them
  - transformers/pvc-update-transformer.yaml # Remove volumename and storage class from PVCs  
  # - transformers/pv-nodename-transformer.yaml # Set PV node affinity node names on PVs
