apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- secrets/pihole-secret.yaml

namespace: pihole

patches:
  - target:
      kind: HTTPRoute
      name: pihole
      namespace: pihole
      group: gateway.networking.k8s.io
      version: v1
    path: patches/patch-pihole-route.yaml
  - target:
      kind: Service
      name: pihole
      namespace: pihole
      group: ""
      version: v1
    path: patches/patch-pihole-svc-lbip.yaml
  - target:
      kind: ConfigMap
      name: pihole-cm
      namespace: pihole
    path: patches/patch-pihole-cm-dns.yaml
    


