apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-store
  # namespace: external-secrets
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "your-azure-tenant-id-placeholder" # populated from kustomize replacement
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "your-keyvault-url-placeholder" # populated from kustomize replacement
      authSecretRef:
        # Points to the secret that contains the azure service principal credentials.
        # Secret is created on cluster bootrap from bootstrap/secrets/azure-key-vault-secret.yaml (example file in git repo)
        # The Secrets must reside in the external-secrets namespace
        clientId:
          name: azure-key-vault-secret  # Secret is created on cluster bootrap from bootstrap/secrets/azure-key-vault-secret.yaml
          namespace: external-secrets  # The Secrets must reside in the external-secrets namespace
          key: ClientID                 # The Secrets must reside in the external-secrets namespace
        clientSecret:
          name: azure-key-vault-secret
          namespace: external-secrets
          key: ClientSecret


        