apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: grafana-cloud-credentials   # K8s Secret name Helm will reference
    creationPolicy: Owner
  data:
    - secretKey: metrics-username
      remoteRef:
        key: grafana-cloud-metrics-username
    - secretKey: metrics-password
      remoteRef:
        key: grafana-cloud-metrics-password
    - secretKey: logs-username
      remoteRef:
        key: grafana-cloud-logs-username
    - secretKey: logs-password
      remoteRef:
        key: grafana-cloud-logs-password
