---
- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true

- name: Check if swap is enabled
  ansible.builtin.shell:
    cmd: swapon --show
  register: swap_info
  changed_when: false # This task doesn't change the system

- name: Disable swap (if enabled)
  ansible.builtin.shell:
    cmd: swapoff -a
  when: swap_info.stdout_lines | length > 0 # Only run if swap is enabled

- name: Comment out swap entries in /etc/fstab (to prevent swap from being enabled on boot)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: "^([^#].*swap.*)$"
    replace: '# \1'
    backup: true

- name: "Create working temp dir for downloads etc if it does not exist: {{ work_dir }}"
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: directory
    mode: "u=rwx,a=rx"

- name: Download containerd official binaries archive and verify checksum
  ansible.builtin.get_url:
    url: "{{ containerd }}"
    dest: "{{ work_dir }}"
    checksum: "sha256:{{ containerd_cksum }}"
    mode: "a=r"
  register: get_containerd_result

- name: Extract containerd archive to /usr/local
  ansible.builtin.unarchive:
    src: "{{ work_dir }}/{{ containerd.split('/')[-1:] | join('') }}" # Extract pkg file name
    dest: /usr/local
    remote_src: true # The archive is already on the remote host
    mode: "a=rx"
  when:
    - get_containerd_result is succeeded
    - not ansible_check_mode

- name: Download the containerd.service unit file to /etc/systemd/system/containerd.service
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /etc/systemd/system/containerd.service
    mode: "u+rwx,g=rx,o=rx"

- name: Create /etc/containerd directory if it does not exist
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Create default containerd config file
  ansible.builtin.shell:
    cmd: "containerd config default > /etc/containerd/config.toml"
    creates: /etc/containerd/config.toml

- name: 'Enable systemd cgroup driver in /etc/containerd/config.toml with runc (note: all occurances set as "SystemdCgroup = true")'
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(.*SystemdCgroup\s*=\s*)false'
    replace: '\1true'
    backup: true
  when: not ansible_check_mode

- name: Enable and start containerd.service
  ansible.builtin.systemd:
    name: containerd.service
    state: started
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode

- name: "Download checksum (sha256) file of runc binary"
  ansible.builtin.get_url:
    url: "{{ runc_cksum }}"
    dest: "{{ work_dir }}/runc.sha256sum"
    mode: "a=r"
  register: get_url_cksum_result # Register the result of the get_url task
  when: not ansible_check_mode

- name: Read the checksum file into a variable
  ansible.builtin.slurp:
    path: "{{ work_dir }}/runc.sha256sum"
  register: checksum_file_content
  when:
    - not ansible_check_mode
    - get_url_cksum_result is succeeded

- name: Set the runc checksum variable
  ansible.builtin.set_fact:
    runc_checksum: "{{ checksum_file_content['content'] | b64decode |
      split('\n') | select('search', 'runc.amd64') | join(' ') |
      split(' ') | first | trim }}"
  when:
    - not ansible_check_mode
    - checksum_file_content is defined
    - checksum_file_content is not failed

- name: Download and verify runc official binary
  ansible.builtin.get_url:
    url: "{{ runc }}"
    dest: /usr/local/sbin/runc
    checksum: "sha256:{{ runc_checksum }}"
    mode: "755"
  when:
    - runc_checksum is defined
    - runc_checksum | length > 1
