apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - signalk-ns.yaml
  - signalk-deployment.yaml
  # - signalk-pv.yaml
  - signalk-pvc.yaml
  - signalk-svc.yaml
  - signalk-route.yaml

namespace: signalk