apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jellyfin
  name: jellyfin-config-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-pvc
  namespace: jellyfin
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-media
