apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jellyfin-ns.yaml
  - jellyfin-deployment.yaml
  # - jellyfin-pv.yaml
  - jellyfin-pvc.yaml
  - jellyfin-svc.yaml
  - jellyfin-route.yaml

namespace: jellyfin

labels:
  - pairs:
      app.kubernetes.io/name: jellyfin
    includeSelectors: false
    includeTemplates: true
