# Update nodeName in PVs to match current node name, or add node affinity to restrict PV to specific node(s).
# Only pvs with label kustomize/app-pv: "true" are affected.
# Use with pv-label-transformer.yaml to select all PVs that should be updated.
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: pv-nodenameupdate-transformer
patch: |-
  - op: replace
    path: /spec/nodeAffinity/required/nodeSelectorTerms/0/matchExpressions/0/values #/0
    value: 
      - "k8s-node-1"
target:
  kind: PersistentVolume
  labelSelector: "kustomize/app-pv=true"
