apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# No resources here, flux will apply infra, apps and this cluster wide kustomizations separately
resources: []

# labels:
#   - pairs:
#       app.kubernetes.io/managed-by: kustomize
#     includeSelectors: false
#     includeTemplates: true




