apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pihole-svc.yaml
  - pihole-ns.yaml
  - pihole-pv.yaml
  - pihole-deployment.yaml
  - pihole-pvc.yaml
  - pihole-route.yaml
  - pihole-cm.yaml
  # - pihole-secret.yaml # Secret is created in cluster kustomization

namespace: pihole
