apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-pvc
  namespace: pihole
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
  volumeName: pihole-etc-pv