apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: azure-store
    namespace: authentik
spec:
    configuration:
        destinationPath: ENC[AES256_GCM,data:oAk4zg/4zoFxyjf/LFozvmDJfH1aAgl7PcBJpv5f8UhDMhtS2Uav0j/0EXEg9HgNOi3Nx736moixbX4Drmo=,iv:bmNIYwfOj1TZhuxJnmQaMIr+LYHhFnlbNar14dbb4qM=,tag:9oCVNwkIcldOgn3Qmumb5w==,type:str]
sops:
    age:
        - recipient: age1gvddufnnp3pdz8vu4cjylzzznt987ju05u7l9t8x4nefaylpu4aq7lvrxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY09XVkJWNlpKa2dxMGZD
            SjBmME1zM0ZJeTN6LzJ6cGt6cEs1bUszeHdnCnhLcFY3QkJUd3V4WXNNek5kV05C
            TDllQzJLcGtyRlV2ZXhoK1lOS0xlUmMKLS0tIG5zRDhkWXlMV1cxcndka2pIbXBu
            NWZtSVc0TkxReCtOcnFxd2psK05kTkUKmo2scZeOoPG5mSkvrOank1rlHhPyQOPd
            YyQjK08EDOV5LArlQ4TKC7xemxKcSMMAbt64pn0Ra6jkms+/2FYIVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T12:59:40Z"
    mac: ENC[AES256_GCM,data:Msur/LDDNtVrMmAD6fA2S9Bm915+ZWFmp8TNl5M2ECPFZ2So2CrRpZnrdHNGOH3H0orCEVpboVITxXFY359dJ1TgsmlZkJCHHW+BZPvBO+TsjMxvdyLvTZzvZxnAbCTWRubTcSKD4HKnhcKScSIwl838gZXledYEMWSMYAujQ2M=,iv:YTAHwLWx5QtNIqi7ukQhRETB8pNDKE9pi3n42YAUsiw=,tag:GuPnVoHyx5MH9v9TT+qGjw==,type:str]
    encrypted_regex: ^(data|stringData|tenantId|vaultUrl|destinationPath)$
    version: 3.10.2
