apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: azure-store
    namespace: authentik
spec:
    configuration:
        destinationPath: ENC[AES256_GCM,data:arwlszHV12kkZb4QhDW6Vor1joAI9mOGoVtlN87zzUoD+lgeO7ONzRHTN7jti43skv+U7fDNaDVRaAVpOw==,iv:refm7tspst8v+Ks3aivQ7CAr+Lg1ymAYVh74Hoi170o=,tag:CZTmPaOlTmJ9AGvoZO5lqQ==,type:str]
sops:
    age:
        - recipient: age1gvddufnnp3pdz8vu4cjylzzznt987ju05u7l9t8x4nefaylpu4aq7lvrxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY09XVkJWNlpKa2dxMGZD
            SjBmME1zM0ZJeTN6LzJ6cGt6cEs1bUszeHdnCnhLcFY3QkJUd3V4WXNNek5kV05C
            TDllQzJLcGtyRlV2ZXhoK1lOS0xlUmMKLS0tIG5zRDhkWXlMV1cxcndka2pIbXBu
            NWZtSVc0TkxReCtOcnFxd2psK05kTkUKmo2scZeOoPG5mSkvrOank1rlHhPyQOPd
            YyQjK08EDOV5LArlQ4TKC7xemxKcSMMAbt64pn0Ra6jkms+/2FYIVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T14:43:20Z"
    mac: ENC[AES256_GCM,data:v3/QDC7wOqf5/2n+81v7sYxWFU4skQF2Wf8rhuGT00ZIgBlbV3Fhgo2iOEZt5CS/dB2aNU0bumVqGY6r+hDAXeC1/DCUeruna+Rnnj8ktk/c64Zkk7cdO1mjhXABTjFWDougt7pubHVmbk2GstIL5UJfmie7/ifjCyE+5bStpzc=,iv:AUUuo4iWU3zYn7mVl3rzoKRmQiV8uTYmAEroO1/84Eo=,tag:Na0gQWRjWhI0oEtvM25/Fw==,type:str]
    encrypted_regex: ^(data|stringData|tenantId|vaultUrl|destinationPath)$
    version: 3.10.2
