---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-addresspool
  namespace: metallb-system
spec:
  addresses:
  - 0.0.0.0/32  # placeholder, will be patched
  autoAssign: true
