---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  chart:
    spec:
      chart: ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
      version: ~0.21.0
      valuesFiles:
        - values.yaml
  install:
    createNamespace: true
  interval: 24h0m0s
