apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../homepage/home-dev
  - ../jellyfin/home-dev
  - ../omada-controller/home-dev
  - ../pihole/home-dev
  - ../signalk/home-dev

images:
  - name: docker.io/tihal/omada-controller
    newTag: "5.15.24.18"
  - name: docker.io/jellyfin/jellyfin
    newTag: "10.10.7"
  - name: docker.io/pihole/pihole
    newTag: "2025.08.0"
  - name: ghcr.io/gethomepage/homepage
    newTag: latest  
  - name: docker.io/signalk/signalk-server
    newTag: latest
  

transformers:
  - transformers/pvc-labeler-transformer.yaml # Add label to all pvcs to let pvc-update-transformer.yaml select them
  - transformers/pvc-update-transformer.yaml # Remove volumename and/or storage class from PVCs

# labels:
#   - pairs:
#       app.kubernetes.io/managed-by: kustomize
#     includeSelectors: false
#     includeTemplates: true
