---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: "~0.19.2"
#      valuesFiles:
#        - values.yaml
  releaseName: external-secrets
  interval: 6h0m0s
  # timeout: 10m0s

  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-values
      valuesKey: values.yaml

  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 2
      remediateLastFailure: true

  upgrade:
    remediation:
      retries: 2
      remediateLastFailure: true