apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-store-credentials # name of the ExternalSecret
  namespace: authentik
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store

  target:
    name: azure-store-credentials  # This secret stores Azure credentials (tenant ID, client ID, and client secret) ...
    creationPolicy: Owner          # for accessing Azure Blob Storage used by the PostgreSQL backup plugin.

  data:
  - secretKey: tenant-id
    remoteRef:
      key: azure-tenant-id
  - secretKey: client-id
    remoteRef:
      key: azure-backup-store-client-id
  - secretKey: client-secret
    remoteRef:
      key: azure-backup-store-client-secret
