apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: azure-store
    namespace: authentik
spec:
    configuration:
        destinationPath: ENC[AES256_GCM,data:3HhLVTlEliSRlqrNdhPgwtDaR0Pf6vYvJ+2FTSFAaiPRsS1psLEXHSakYn0143KNXIg5TD3+CFQVEHlh,iv:Ma9aWodd6Pe+ksmE9QWYrmeC5lfjQjQEsTb5hfn7YiE=,tag:FQlyJ3WZnMYyxdvhvzT0YA==,type:str]
sops:
    age:
        - recipient: age1gvddufnnp3pdz8vu4cjylzzznt987ju05u7l9t8x4nefaylpu4aq7lvrxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY09XVkJWNlpKa2dxMGZD
            SjBmME1zM0ZJeTN6LzJ6cGt6cEs1bUszeHdnCnhLcFY3QkJUd3V4WXNNek5kV05C
            TDllQzJLcGtyRlV2ZXhoK1lOS0xlUmMKLS0tIG5zRDhkWXlMV1cxcndka2pIbXBu
            NWZtSVc0TkxReCtOcnFxd2psK05kTkUKmo2scZeOoPG5mSkvrOank1rlHhPyQOPd
            YyQjK08EDOV5LArlQ4TKC7xemxKcSMMAbt64pn0Ra6jkms+/2FYIVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T10:16:35Z"
    mac: ENC[AES256_GCM,data:cdb/4eVnSKmIS2mh5SasKVjwp7vkDnqXPBvpkUuncgR74ueDE6bGaUrnEsbZIT7/2CYQaNxc6JyWrM9/8gKNtPtQXWuhqFfemve4J/JShGO8236b14nudk9eASSN/ibgMP7dq5EBZtCPgPQmgI3Y1AXt4cDZx9QmkLBQtbOfOuI=,iv:4YqIc8AgyJWybJFLRj3XTxzowCKGb79vrrK5/5u42gA=,tag:yHjrpdqWBIxsG4qvjYuqyA==,type:str]
    encrypted_regex: ^(data|stringData|tenantId|vaultUrl|destinationPath)$
    version: 3.10.2
