apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: azure-store
    namespace: authentik
spec:
    configuration:
        destinationPath: ENC[AES256_GCM,data:520uey5rPRVi/brJqadfx2EYlnnpqNS1LKnSfIBTJoByg8focVYEAJqMxFr2v2VQpVcQ9A6sxOTqHL+Ilw==,iv:J5sJPuvN9zPcZvn1p9ZYpqNF59KiVgjrYPZ3nhbhJT4=,tag:RO/Avl2bhi7oe98VQTzmkQ==,type:str]
sops:
    age:
        - recipient: age1gvddufnnp3pdz8vu4cjylzzznt987ju05u7l9t8x4nefaylpu4aq7lvrxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY09XVkJWNlpKa2dxMGZD
            SjBmME1zM0ZJeTN6LzJ6cGt6cEs1bUszeHdnCnhLcFY3QkJUd3V4WXNNek5kV05C
            TDllQzJLcGtyRlV2ZXhoK1lOS0xlUmMKLS0tIG5zRDhkWXlMV1cxcndka2pIbXBu
            NWZtSVc0TkxReCtOcnFxd2psK05kTkUKmo2scZeOoPG5mSkvrOank1rlHhPyQOPd
            YyQjK08EDOV5LArlQ4TKC7xemxKcSMMAbt64pn0Ra6jkms+/2FYIVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T12:57:36Z"
    mac: ENC[AES256_GCM,data:vzUBpHFfJYt9HZgitMLI5W+ABYQnifYHURHHb8jRIx2XDG+q1QwrshSpJSgnCOoxrP57wfmSwX/KIde48Kg8nRuIAjqLjfdxMFHoLeCezL7t01mPikm9W3x+e829dPsz1v0h3g5NRs8mQ8IoYfNXZcwYuj2ROUap8dgEaL6Ah6s=,iv:NXNiW0OeBLRi8heGwmtuHEF7MZ6iUAmqnpPW7dzKkt0=,tag:5VudOk/N1J3YJXqFtewQMA==,type:str]
    encrypted_regex: ^(data|stringData|tenantId|vaultUrl|destinationPath)$
    version: 3.10.2
