name: update-flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Set CLUSTER_NAME
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"

          if [ "$BRANCH_NAME" = "main" ]; then
            CLUSTER_NAME="home-prod"
          elif [ "$BRANCH_NAME" = "dev" ]; then
            CLUSTER_NAME="home-dev"
          else
            CLUSTER_NAME="home-test"
          fi
          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
          echo "Using cluster name: ${CLUSTER_NAME}"
      - name: Check for updates
        id: update
        run: |
          flux install \
            --export > ./kubernetes/clusters/${CLUSTER_NAME}/flux-system/gotk-components.yaml
          VERSION="$(flux -v)"
          echo "flux_version=$VERSION" >> $GITHUB_OUTPUT          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
            branch: update-flux
            commit-message: Update to ${{ steps.update.outputs.flux_version }}
            title: Update to ${{ steps.update.outputs.flux_version }}
            body: |
              ${{ steps.update.outputs.flux_version }} 
