name: GitOps Validation CI 

# Controls when the workflow will run
on:
  # The workflow will run for pull requests targeting the main or dev branches, and for pushes to any branch except main.
  # Main branch is protected, so direct pushes are not allowed. All changes must go through a pull request.
  # Dev branch is the development branch where all feature branches are merged. Direct pushes are allowed as this is a homelab environment only. 

  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main","dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  security-scan: # run a security scan using Gitleaks to detect any secrets in the codebase.
    runs-on: ubuntu-latest
    permissions:
      contents: read      # Required to checkout the code
      pull-requests: read  # Required for Gitleaks to scan PR commits
      statuses: write      # Required if the action updates the PR status check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-manifests: # Validate the Flux Kustomization files in the clusters directory.
    # if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      FLUX_CLUSTER_DIR: ./kubernetes/clusters

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: 'latest'
      
      - name: Check Flux CLI version
        run: flux --version

      - name: Validate Flux Kustomization files
        run: |
          set -e # Fail immediately if any command fails
          for ks_file in ${FLUX_CLUSTER_DIR}/*/*.yaml; do
            if [[ $(yq .kind $ks_file) == "Kustomization" ]]; then
              ks_name=$(yq .metadata.name $ks_file)
              ks_path=$(yq .spec.path $ks_file)              
              echo "::group::Validating [$ks_file] in cluster $(dirname $ks_file | xargs basename ) with Kustomization name $ks_name"
              flux build kustomization $ks_name \
                --path $ks_path \
                --kustomization-file $ks_file \
                --dry-run > /dev/null
              echo "::endgroup::"
            else
              echo "::group::Skipping $ks_file as it is not a Kustomization file."  
              echo "::endgroup::"
            fi
          done
